services:
  - type: web
    name: bot-archive
    env: python
    buildCommand: pip install -r requisitos.txt
    startCommand: python3 app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
